import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowDown, ArrowUpRight, Check, CircleDot, Cpu, Github, HardDrive, LockKeyhole, Mail, Server, Terminal } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Octane — Systems & Gameplay Developer" },
      { name: "description", content: "Портфолио Octane: GLua, Python, системное администрирование, игровой хостинг и исследования." },
      { property: "og:title", content: "Octane — Systems & Gameplay Developer" },
      { property: "og:description", content: "GLua, Python, серверная инфраструктура и исследовательские работы." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/" }],
  }),
  component: Index,
});

type Language = "ru" | "uk" | "en";

const copy = {
  ru: {
    nav: ["исследования", "гейммоды", "python", "системы", "контакты"], available: "на связи", hero: "Я пишу игровые системы на GLua, делаю инструменты на Python, настраиваю серверы и занимаюсь кибербезопасностью.", contact: "Связаться", scroll: "к исследованиям",
    researchTitle: "Исследовательские работы / МАН", researchCaption: "Здесь мои более серьёзные работы: кибербезопасность, программная инженерия и надёжность кода, который пишет ИИ.", completed: "завершено", denied: "ДОСТУП ЗАКРЫТ", deniedText: "Эту работу по кибербезопасности я пока не публикую.", inProgress: "в работе", lmcText: "Я разрабатываю метод для случаев, когда ИИ плохо знает нишевый язык или API. Смысл простой: не угадывать функцию, а сначала найти её в документации, проверить версию и только потом писать код.", steps: ["Разобрать задачу", "Найти и проверить API", "Написать и проверить код"], hypothesis: "Гипотеза", hypothesisText: "Если проверять API заранее, выдуманных функций станет меньше, а рабочий результат получится быстрее.", metrics: "Что измеряю", metricsText: "Несуществующие вызовы, ошибки аргументов и версий, запускаемость кода и число исправлений.",
    gmTitle: "Garry’s Mod / GLua", gmCaption: "Два режима, которые я пишу на чистом GLua — без сторонних фреймворков и внутриигровых конструкторов.", gmTexts: ["Полноценный RTS-гейммод с нуля: свои метатаблицы и сущности, серверная логика и оптимизированный netcode.", "Нишевый режим со своей механикой, быстрым VGUI и безопасной работой с игровыми данными."], pending: "Steam Workshop / ссылка позже",
    pythonTitle: "Python & Автоматизация", pythonCaption: "На Python я делаю ботов, сбор данных и инструменты для серверов и аудио.", pythonItems: [["Telegram-боты / Мониторинг", "Боты следят за игровыми серверами через RCON, присылают алерты и помогают с обычными задачами администратора."], ["Async / Парсинг", "Собираю и обрабатываю данные через asyncio и aiohttp, в том числе статистику и серверные логи."], ["DSP / Аудио", "Работаю с аудио в реальном времени через pedalboard, sounddevice и FFmpeg: фильтрация, обработка и конвертация."]],
    systemsTitle: "Системное администрирование, Linux & Hardware", systemsCaption: "Я умею работать не только с кодом, но и с системой и самим железом.", systemItems: [["Linux & Windows", "Ставлю, размечаю и настраиваю Linux и Windows. Поднимаю серверное окружение через терминал, настраиваю systemd, SSH и сетевые правила."], ["Обслуживание ПК", "Могу найти аппаратную проблему, заменить охлаждение и термоинтерфейсы, поставить новые комплектующие и нормально проверить результат."], ["Системный дебаг", "Ищу причины перегрева, ошибок памяти, конфликтов драйверов и нестабильности под нагрузкой. Провожу стресс-тесты и смотрю, где именно ломается система."]],
    hostingTitle: "Инфраструктура & Игровой хостинг", hostingCaption: "Разворачивал серверы с нуля и связывал их с веб-сервисами, базами и мониторингом.", hostingItems: [["Dedicated & VPS", "Работал с выделенными и виртуальными серверами на Linux и Windows: первичная настройка, доступы, безопасность и дальнейшее администрирование."], ["Game Server Hosting", "Разворачиваю Garry’s Mod, Minecraft и другие игровые серверы: порты, автозапуск, демоны, FastDL и оптимизация RAM/CPU."], ["Веб и интеграции", "Настраиваю Nginx или Apache, DNS и SSL. Подключаю панели, MySQL/SQLite, донат-системы и автоматическую выдачу привилегий."], ["Мониторинг", "Настраиваю алерты при падении, RCON-управление и сбор логов, чтобы проблему было видно сразу, а не после жалоб игроков."]],
    stackTitle: "Технический стек", stackCaption: "То, с чем я реально работаю.", stackAreas: ["Garry's Mod / GLua", "Python", "Research / Security", "Инструменты"], securityStack: "Анализ уязвимостей · проверка API · техническая документация", tooling: "Git / GitHub · VS Code · Linux · Hammer++",
    principlesTitle: "Как я работаю", principlesCaption: "Несколько вещей, которые для меня обязательны.", principles: [["Сначала план", "Сначала разбираюсь в задаче и ограничениях, потом пишу код."], ["Anti-Exploit", "Не доверяю данным от клиента: каждый net-запрос проверяется на сервере."], ["Слежу за нагрузкой", "Не оставляю лишний сетевой трафик, тяжёлые циклы и утечки памяти."], ["Не пропадаю после сдачи", "Помогаю с запуском, ищу причины ошибок и исправляю их."]],
    contactLabel: "СВЯЗЬ", contactTitle: "Можно обсудить задачу", contactText: "GLua, серверная логика, Python, Linux, хостинг или исследовательская работа.", footer: "Сделано вручную, без шаблонов.", soon: "скоро",
  },
  uk: {
    nav: ["дослідження", "гейммоди", "python", "системи", "контакти"], available: "на зв’язку", hero: "Я пишу ігрові системи на GLua, роблю інструменти на Python, налаштовую сервери та займаюся кібербезпекою.", contact: "Зв’язатися", scroll: "до досліджень",
    researchTitle: "Дослідницькі роботи / МАН", researchCaption: "Тут мої серйозніші роботи: кібербезпека, програмна інженерія та надійність коду, який пише ШІ.", completed: "завершено", denied: "ДОСТУП ЗАКРИТО", deniedText: "Цю роботу з кібербезпеки я поки не публікую.", inProgress: "в роботі", lmcText: "Я розробляю метод для випадків, коли ШІ погано знає нішеву мову або API. Сенс простий: не вгадувати функцію, а спочатку знайти її в документації, перевірити версію і лише потім писати код.", steps: ["Розібрати задачу", "Знайти й перевірити API", "Написати й перевірити код"], hypothesis: "Гіпотеза", hypothesisText: "Якщо перевіряти API заздалегідь, вигаданих функцій стане менше, а робочий результат з’явиться швидше.", metrics: "Що вимірюю", metricsText: "Неіснуючі виклики, помилки аргументів і версій, запуск коду та кількість виправлень.",
    gmTitle: "Garry’s Mod / GLua", gmCaption: "Два режими, які я пишу на чистому GLua — без сторонніх фреймворків та внутрішньоігрових конструкторів.", gmTexts: ["Повноцінний RTS-гейммод з нуля: власні метатаблиці та сутності, серверна логіка й оптимізований netcode.", "Нішевий режим зі своєю механікою, швидким VGUI та безпечною роботою з ігровими даними."], pending: "Steam Workshop / посилання згодом",
    pythonTitle: "Python & Автоматизація", pythonCaption: "На Python я роблю ботів, збір даних та інструменти для серверів і аудіо.", pythonItems: [["Telegram-боти / Моніторинг", "Боти стежать за ігровими серверами через RCON, надсилають сповіщення та допомагають зі звичайними задачами адміністратора."], ["Async / Парсинг", "Збираю й обробляю дані через asyncio та aiohttp, зокрема статистику і серверні логи."], ["DSP / Аудіо", "Працюю з аудіо в реальному часі через pedalboard, sounddevice та FFmpeg: фільтрація, обробка і конвертація."]],
    systemsTitle: "Системне адміністрування, Linux & Hardware", systemsCaption: "Я вмію працювати не лише з кодом, а й із системою та самим залізом.", systemItems: [["Linux & Windows", "Встановлюю, розмічаю та налаштовую Linux і Windows. Підіймаю серверне середовище через термінал, налаштовую systemd, SSH і мережеві правила."], ["Обслуговування ПК", "Можу знайти апаратну проблему, замінити охолодження й термоінтерфейси, встановити нові комплектуючі та нормально перевірити результат."], ["Системний дебаг", "Шукаю причини перегріву, помилок пам’яті, конфліктів драйверів і нестабільності під навантаженням. Проводжу стрес-тести й дивлюся, де саме ламається система."]],
    hostingTitle: "Інфраструктура & Ігровий хостинг", hostingCaption: "Розгортав сервери з нуля та зв’язував їх із вебсервісами, базами й моніторингом.", hostingItems: [["Dedicated & VPS", "Працював із виділеними й віртуальними серверами на Linux та Windows: первинне налаштування, доступи, безпека і подальше адміністрування."], ["Game Server Hosting", "Розгортаю Garry’s Mod, Minecraft та інші ігрові сервери: порти, автозапуск, демони, FastDL й оптимізація RAM/CPU."], ["Веб та інтеграції", "Налаштовую Nginx або Apache, DNS і SSL. Підключаю панелі, MySQL/SQLite, донат-системи й автоматичну видачу привілеїв."], ["Моніторинг", "Налаштовую сповіщення при падінні, RCON-керування та збір логів, щоб проблему було видно одразу, а не після скарг гравців."]],
    stackTitle: "Технічний стек", stackCaption: "Те, з чим я реально працюю.", stackAreas: ["Garry's Mod / GLua", "Python", "Research / Security", "Інструменти"], securityStack: "Аналіз вразливостей · перевірка API · технічна документація", tooling: "Git / GitHub · VS Code · Linux · Hammer++",
    principlesTitle: "Як я працюю", principlesCaption: "Кілька речей, які для мене обов’язкові.", principles: [["Спочатку план", "Спочатку розбираюся в задачі й обмеженнях, потім пишу код."], ["Anti-Exploit", "Не довіряю даним від клієнта: кожен net-запит перевіряється на сервері."], ["Стежу за навантаженням", "Не залишаю зайвий мережевий трафік, важкі цикли та витоки пам’яті."], ["Не зникаю після здачі", "Допомагаю із запуском, шукаю причини помилок та виправляю їх."]],
    contactLabel: "ЗВ’ЯЗОК", contactTitle: "Можемо обговорити задачу", contactText: "GLua, серверна логіка, Python, Linux, хостинг або дослідницька робота.", footer: "Зроблено вручну, без шаблонів.", soon: "скоро",
  },
  en: {
    nav: ["research", "gamemodes", "python", "systems", "contact"], available: "available", hero: "I build game systems in GLua, write Python tools, configure servers, and work on cybersecurity research.", contact: "Contact me", scroll: "view research",
    researchTitle: "Research / Junior Academy", researchCaption: "This is my more serious work: cybersecurity, software engineering, and making AI-written code more reliable.", completed: "completed", denied: "ACCESS DENIED", deniedText: "I am not publishing this cybersecurity paper yet.", inProgress: "in progress", lmcText: "I am developing a method for cases where AI does not know a niche language or API well. The idea is simple: do not guess a function. Find it in the documentation, check the version, and only then write the code.", steps: ["Break down the task", "Find and verify the API", "Write and check the code"], hypothesis: "Hypothesis", hypothesisText: "Checking an API first should reduce made-up functions and get to working code faster.", metrics: "What I measure", metricsText: "Nonexistent calls, argument and version errors, runnable code rate, and correction rounds.",
    gmTitle: "Garry’s Mod / GLua", gmCaption: "Two modes I am building in plain GLua, without third-party frameworks or in-game builders.", gmTexts: ["A complete RTS gamemode built from scratch: custom metatables and entities, server logic, and optimized netcode.", "A niche mode with its own mechanics, fast VGUI, and safe handling of game data."], pending: "Steam Workshop / link later",
    pythonTitle: "Python & Automation", pythonCaption: "I use Python for bots, data collection, and tools for servers and audio.", pythonItems: [["Telegram Bots / Monitoring", "My bots monitor game servers through RCON, send alerts, and handle routine admin tasks."], ["Async / Parsing", "I collect and process data with asyncio and aiohttp, including statistics and server logs."], ["DSP / Audio", "I work with real-time audio using pedalboard, sounddevice, and FFmpeg for filtering, processing, and conversion."]],
    systemsTitle: "System Administration, Linux & Hardware", systemsCaption: "I can work with the operating system and physical hardware, not only code.", systemItems: [["Linux & Windows", "I install, partition, and configure Linux and Windows. I set up server environments from the terminal, including systemd, SSH, and network rules."], ["PC Maintenance", "I diagnose hardware faults, replace cooling and thermal interfaces, upgrade components, and test the result properly."], ["System Debugging", "I trace overheating, memory errors, driver conflicts, and instability under load. I run stress tests to find the actual failure point."]],
    hostingTitle: "Infrastructure & Game Hosting", hostingCaption: "I have deployed servers from scratch and connected them to web services, databases, and monitoring.", hostingItems: [["Dedicated & VPS", "I have managed Linux and Windows dedicated and virtual servers: initial setup, access, security, and ongoing administration."], ["Game Server Hosting", "I deploy Garry’s Mod, Minecraft, and other game servers: ports, startup services, daemons, FastDL, and RAM/CPU optimization."], ["Web & Integrations", "I configure Nginx or Apache, DNS, and SSL. I connect panels, MySQL/SQLite, donation systems, and automatic privilege delivery."], ["Monitoring", "I set up downtime alerts, RCON control, and log collection so a problem is visible before players have to report it."]],
    stackTitle: "Technical Stack", stackCaption: "The tools I actually work with.", stackAreas: ["Garry's Mod / GLua", "Python", "Research / Security", "Tools"], securityStack: "Vulnerability analysis · API verification · technical documentation", tooling: "Git / GitHub · VS Code · Linux · Hammer++",
    principlesTitle: "How I Work", principlesCaption: "A few things I consider mandatory.", principles: [["Plan first", "I understand the task and constraints before writing code."], ["Anti-Exploit", "I do not trust client data: every net request is validated on the server."], ["Watch performance", "I avoid unnecessary network traffic, heavy loops, and memory leaks."], ["Stay after delivery", "I help with launch, track down errors, and fix them."]],
    contactLabel: "CONTACT", contactTitle: "Let’s discuss the task", contactText: "GLua, server logic, Python, Linux, hosting, or research work.", footer: "Built by hand, without templates.", soon: "soon",
  },
} as const;

function Label({ children }: { children: ReactNode }) { return <span className="font-mono text-xs uppercase text-primary">{children}</span>; }
function SectionHeading({ index, title, caption }: { index: string; title: string; caption: string }) { return <div className="mb-8 grid gap-3 border-b border-border pb-5 md:grid-cols-[8rem_1fr]"><span className="font-mono text-xs text-signal-muted">/{index}</span><div><h2 className="font-mono text-2xl font-semibold text-foreground md:text-3xl">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{caption}</p></div></div>; }

function Index() {
  const [language, setLanguage] = useState<Language>("en");
  useEffect(() => {
    const saved = window.localStorage.getItem("octane-language");
    if (saved === "uk" || saved === "en") setLanguage(saved);
  }, []);
  useEffect(() => { document.documentElement.lang = language; window.localStorage.setItem("octane-language", language); }, [language]);
  const t = copy[language];
  const stack = [[t.stackAreas[0], "GLua Engine · VGUI · Netcode · Server authority · Anti-Exploit · Metatables"], [t.stackAreas[1], "asyncio · Aiogram / Telebot · FFmpeg · Pedalboard · Web Scraping"], [t.stackAreas[2], t.securityStack], [t.stackAreas[3], t.tooling]];
  const languageNames: Record<Language, string> = { uk: "UA", en: "EN" };

  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex min-h-14 max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-2 lg:px-8"><a href="#top" className="flex items-center gap-2 font-mono text-sm font-semibold"><Terminal className="size-4 text-primary" /> octane@dev:~$</a><nav className="order-3 hidden w-full items-center gap-6 font-mono text-[11px] uppercase text-muted-foreground md:order-none md:flex md:w-auto" aria-label="Navigation">{t.nav.map((item, i) => <a key={item} className="transition-colors hover:text-primary" href={["#research", "#gamemodes", "#python", "#systems", "#contact"][i]}>{item}</a>)}</nav><div className="flex items-center gap-3"><div className="flex border border-border" aria-label="Language">{(["uk", "en"] as Language[]).map(code => <Button key={code} type="button" variant="ghost" size="sm" aria-pressed={language === code} onClick={() => setLanguage(code)} className={cn("h-7 min-w-9 rounded-none border-r border-border px-2 font-mono text-[10px] last:border-r-0", language === code && "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground")}>{languageNames[code]}</Button>)}</div><span className="hidden items-center gap-2 font-mono text-[10px] uppercase text-primary sm:flex"><span className="size-1.5 bg-primary" />{t.available}</span></div></div></header>

    <section id="top" className="relative mx-auto flex min-h-[calc(100vh-3.5rem)] max-w-7xl flex-col justify-center px-5 py-16 lg:px-8"><div className="scanline pointer-events-none absolute inset-0 opacity-20" /><div className="relative max-w-5xl reveal"><div className="mb-8 flex flex-wrap gap-x-6 gap-y-2 border-l-2 border-primary pl-4 font-mono text-[11px] uppercase text-muted-foreground"><span>build: 2026.09</span><span>location: ua</span><span>status: operational</span></div><p className="mb-5 font-mono text-sm text-primary">$ whoami</p><h1 className="max-w-5xl font-mono text-4xl font-semibold leading-[1.12] sm:text-6xl lg:text-7xl">Octane<span className="text-primary">_</span><br />Systems &amp; Gameplay Developer</h1><p className="mt-7 max-w-3xl text-base leading-7 text-muted-foreground md:text-lg">{t.hero}</p><div className="mt-9 flex flex-wrap gap-3"><a href="https://github.com/qwerty123qwerty123039578" target="_blank" rel="noreferrer" className={cn(buttonVariants({ variant: "terminal", size: "lg" }))}><Github />GitHub<ArrowUpRight /></a><Button variant="terminalMuted" size="lg" disabled>Telegram / {t.soon}</Button><Button variant="terminalMuted" size="lg" disabled>Discord / {t.soon}</Button><a href="#contact" className={cn(buttonVariants({ variant: "terminalMuted", size: "lg" }))}><Mail />{t.contact}</a></div></div><a href="#research" className="absolute bottom-7 left-5 flex items-center gap-2 font-mono text-[10px] uppercase text-muted-foreground hover:text-primary lg:left-8">{t.scroll}<ArrowDown className="size-3" /></a></section>

    <section id="research" className="border-y border-border bg-terminal py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading index="01" title={t.researchTitle} caption={t.researchCaption} /><div className="grid gap-5 lg:grid-cols-[0.78fr_1.22fr]"><article className="terminal-panel relative min-h-[420px] overflow-hidden p-6 sm:p-8"><div className="absolute inset-x-0 top-0 h-0.5 bg-warning" /><div className="flex items-start justify-between gap-4"><Label>MAN / RESEARCH_01</Label><span className="border border-warning px-2 py-1 font-mono text-[10px] uppercase text-warning">{t.completed}</span></div><div className="flex min-h-[290px] flex-col items-center justify-center text-center"><LockKeyhole className="mb-5 size-10 text-warning" strokeWidth={1.4} /><p className="font-mono text-2xl font-semibold text-warning">{t.denied}</p><p className="mt-3 max-w-xs font-mono text-xs leading-6 text-muted-foreground">{t.deniedText}</p><div className="mt-7 w-full max-w-sm border-t border-dashed border-border pt-4 text-left font-mono text-[10px] leading-5 text-muted-foreground"><p>document.status ........ restricted</p><p>classification ......... MAN archive</p><p>public.summary .......... unavailable</p></div></div></article><article className="terminal-panel p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><Label>MAN / RESEARCH_02</Label><h3 className="mt-3 font-mono text-2xl font-semibold">LMC — Librarian Method Coding</h3></div><span className="border border-primary px-2 py-1 font-mono text-[10px] uppercase text-primary">{t.inProgress}</span></div><p className="mt-6 max-w-3xl text-sm leading-7 text-muted-foreground">{t.lmcText}</p><blockquote className="my-7 border-l-2 border-primary bg-accent/30 px-5 py-4 font-mono text-sm">No Documentation → No API Claim</blockquote><div className="grid gap-4 md:grid-cols-3">{t.steps.map((step, i) => <div key={step} className="border border-border p-4"><span className="font-mono text-[10px] text-primary">0{i + 1}</span><p className="mt-2 text-sm font-medium">{step}</p></div>)}</div><div className="mt-7 grid gap-6 border-t border-border pt-6 md:grid-cols-2"><div><Label>{t.hypothesis}</Label><p className="mt-3 text-sm leading-6 text-muted-foreground">{t.hypothesisText}</p></div><div><Label>{t.metrics}</Label><p className="mt-3 text-sm leading-6 text-muted-foreground">{t.metricsText}</p></div></div><div className="mt-7 flex flex-wrap gap-2 font-mono text-[10px] uppercase text-signal-muted">{["UNKNOWN", "FOUND", "VERIFIED", "VERSION-VERIFIED", "CODE-VERIFIED"].map(item => <span key={item} className="border border-border px-2 py-1.5">{item}</span>)}</div></article></div></div></section>

    <section id="gamemodes" className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading index="02" title={t.gmTitle} caption={t.gmCaption} /><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{[{ name: "Warlord RTS", n: "01", text: t.gmTexts[0], tags: ["METATABLES", "SERVER AUTHORITY", "NETCODE"] }, { name: "AITd", n: "02", text: t.gmTexts[1], tags: ["VGUI", "HAMMER++", "SQL"] }].map(project => <article key={project.name} className="bg-card p-6 sm:p-8"><div className="flex justify-between"><Label>GM_{project.n}</Label><span className="font-mono text-[10px] uppercase text-warning">[ alpha ]</span></div><h3 className="mt-12 font-mono text-3xl font-semibold">{project.name}</h3><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">{project.text}</p><div className="mt-8 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="border border-border px-2 py-1 font-mono text-[10px] text-muted-foreground">{tag}</span>)}</div><Button className="mt-8" variant="terminalMuted" disabled>{t.pending}</Button></article>)}</div></div></section>

    <section id="python" className="border-y border-border bg-terminal py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading index="03" title={t.pythonTitle} caption={t.pythonCaption} /><div className="grid gap-8 md:grid-cols-3">{t.pythonItems.map(([title, text], i) => <article key={title} className="border-t border-primary pt-5"><span className="font-mono text-[10px] text-signal-muted">PY.MOD.0{i + 1}</span><h3 className="mt-4 font-mono text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>

    <section id="systems" className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading index="04" title={t.systemsTitle} caption={t.systemsCaption} /><div className="grid gap-px border border-border bg-border md:grid-cols-3">{t.systemItems.map(([title, text], i) => <article key={title} className="bg-card p-6"><div className="flex items-center justify-between"><Cpu className="size-5 text-primary" /><span className="font-mono text-[10px] text-signal-muted">SYS.0{i + 1}</span></div><h3 className="mt-8 font-mono text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div><div className="mt-16"><SectionHeading index="04.1" title={t.hostingTitle} caption={t.hostingCaption} /><div className="grid gap-8 sm:grid-cols-2">{t.hostingItems.map(([title, text], i) => <article key={title} className="border-l border-border pl-5"><div className="flex items-center gap-3"><span className="font-mono text-[10px] text-primary">HOST.0{i + 1}</span>{i < 2 ? <Server className="size-4 text-signal-muted" /> : <HardDrive className="size-4 text-signal-muted" />}</div><h3 className="mt-4 font-mono text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></div></section>

    <section className="border-y border-border bg-terminal py-20"><div className="mx-auto grid max-w-7xl gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><SectionHeading index="05" title={t.stackTitle} caption={t.stackCaption} /><div className="divide-y divide-border border-y border-border">{stack.map(([area, skills]) => <div key={area} className="grid gap-2 py-5 sm:grid-cols-[11rem_1fr]"><span className="font-mono text-xs text-primary">{area}</span><span className="text-sm leading-6 text-muted-foreground">{skills}</span></div>)}</div></div><div><SectionHeading index="06" title={t.principlesTitle} caption={t.principlesCaption} /><div className="space-y-5">{t.principles.map(([title, text]) => <div key={title} className="flex gap-4"><Check className="mt-0.5 size-4 shrink-0 text-primary" /><div><h3 className="font-mono text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></div></div></section>

    <footer id="contact" className="border-t border-border"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 md:grid-cols-[1fr_auto] md:items-end"><div><Label>{t.contactLabel}</Label><h2 className="mt-4 font-mono text-3xl font-semibold sm:text-4xl">{t.contactTitle}<span className="cursor-blink text-primary">_</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">{t.contactText}</p></div><div className="flex flex-wrap gap-3"><a href="https://github.com/qwerty123qwerty123039578" target="_blank" rel="noreferrer" className={cn(buttonVariants({ variant: "terminal" }))}><Github />GitHub</a><Button variant="terminalMuted" disabled><CircleDot />Telegram / {t.soon}</Button><Button variant="terminalMuted" disabled>Discord / {t.soon}</Button></div></div><div className="mt-14 flex flex-col gap-2 border-t border-border pt-5 font-mono text-[10px] uppercase text-muted-foreground sm:flex-row sm:justify-between"><span>© 2026 Octane</span><span>{t.footer}</span></div></div></footer>
  </main>;
}
